// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FormatBar: typeof import('./src/components/inference/FormatBar.vue')['default']
    'IAkarIcons:cross': typeof import('~icons/akar-icons/cross')['default']
    'IAntDesign:fileMarkdownOutlined': typeof import('~icons/ant-design/file-markdown-outlined')['default']
    'IBi:menuUp': typeof import('~icons/bi/menu-up')['default']
    'ICarbon:network4': typeof import('~icons/carbon/network4')['default']
    'ICil:save': typeof import('~icons/cil/save')['default']
    'ICil:text': typeof import('~icons/cil/text')['default']
    'IDashicons:html': typeof import('~icons/dashicons/html')['default']
    'IEosIcons:bubbleLoading': typeof import('~icons/eos-icons/bubble-loading')['default']
    'IEp:dCaret': typeof import('~icons/ep/d-caret')['default']
    'IEva:options2Outline': typeof import('~icons/eva/options2-outline')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    'IFluent:settings32Regular': typeof import('~icons/fluent/settings32-regular')['default']
    'IGrommetIcons:clear': typeof import('~icons/grommet-icons/clear')['default']
    'IIcomoonFree:stop': typeof import('~icons/icomoon-free/stop')['default']
    'IIconoir:networkAlt': typeof import('~icons/iconoir/network-alt')['default']
    'IIconoir:play': typeof import('~icons/iconoir/play')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    'IMingcute:checkFill': typeof import('~icons/mingcute/check-fill')['default']
    'IMingcute:delete2Line': typeof import('~icons/mingcute/delete2-line')['default']
    InferParams: typeof import('./src/components/inference/InferParams.vue')['default']
    InferResult: typeof import('./src/components/inference/InferResult.vue')['default']
    InferStats: typeof import('./src/components/inference/InferStats.vue')['default']
    'ITabler:prompt': typeof import('~icons/tabler/prompt')['default']
    ModelsPicker: typeof import('./src/components/ModelsPicker.vue')['default']
    PresetsPicker: typeof import('./src/components/PresetsPicker.vue')['default']
    PromptsBar: typeof import('./src/components/PromptsBar.vue')['default']
    PromptTemplate: typeof import('./src/components/inference/PromptTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavePromptDialog: typeof import('./src/components/inference/SavePromptDialog.vue')['default']
    SaveTaskDialog: typeof import('./src/components/inference/SaveTaskDialog.vue')['default']
    SaveTemplateDialog: typeof import('./src/components/inference/SaveTemplateDialog.vue')['default']
    SettingsPopin: typeof import('./src/components/SettingsPopin.vue')['default']
    ShotEditor: typeof import('./src/components/inference/ShotEditor.vue')['default']
    SideBars: typeof import('./src/components/SideBars.vue')['default']
    TasksBar: typeof import('./src/components/TasksBar.vue')['default']
    TemplateEditor: typeof import('./src/components/inference/TemplateEditor.vue')['default']
    TemplatesBar: typeof import('./src/components/TemplatesBar.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
